services:
  - type: web
    name: finance-tracker
    env: docker
    plan: starter
    autoDeploy: true
    region: oregon
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PLAID_CLIENT_ID
        sync: false
      - key: PLAID_SECRET
        sync: false
      - key: PLAID_ENV
        value: sandbox
